version: 0.2
phases:
     install:
        commands:
            - pwd
            - ls
        

     build:
        commands:
          - aws s3 cp src s3://webapp-cca-cw --recursive
     post_build:
        commands:
            - echo $CODEBUILD_RESOLVED_SOURCE_VERSION   
            - COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
            - echo "{\"commitid\":\"$COMMIT_ID\"}">version.json
            - cat version.json 

artifacts:
   files:
      - deploy.sh
      - version.json