version: 0.2
phases:
     install:
        commands:
            - pwd
            - ls
        

     build:
        commands:
          - aws s3 cp ./ s3://webapp-caa-cw

artifacts:
   files:
      - deploy.sh