version: 0.2
phases:
     install:
        commands:
            - pwd
            - ls
        

     build:
        commands:
          - aws s3 cp index.html s3://webapp-cca-cw

artifacts:
   files:
      - deploy.sh